In [ ]:
# Original source - https://gist.github.com/vukrosic/94dc965a22b0892042f44fed25918598

# The notebook worked in google colab using torch==2.9.0 and python 3.12.12
# The code does not work on MacOS x86 Intel because torch 2.4 not supported because
# nn.RMSNorm is available in torch 2.4
# Click Terminal at bottom, run "nvidia smi" for gpu info, "watch -n 1 nvidia smi" to see progress

# After training 2000, 5000, 5000 iterations, you may get "All GPU resources are used", and
# Ask you to switch to CPU, which was very slow
# Wait a little, switch to CPU and then connect to GPU, then continue

# Explanation and comments are removed for brevity, check original source.

import torch
import torch.nn as nn  # Neural network modules like Linear, Embedding, etc.
import torch.nn.functional as F  # Functional interface for operations like cross_entropy, silu, etc.
from torch.utils.data import Dataset, DataLoader  # Base class and utilities for loading datasets
from torch.cuda.amp import autocast, GradScaler  # 🔄 Automatic Mixed Precision (AMP) tools for faster/lower-memory training

import math  # Standard math operations (e.g. sqrt, exp, cos)
import random  # Python's random number utilities (used for seeding)
import numpy as np  # Numerical computing library, used for random seeding and general array ops

from datasets import load_dataset  # 🧁 Hugging Face Datasets library for streaming large datasets
from tqdm import tqdm  # ⏳ Progress bar visualization library, great for loops

import time  # ⌛ Timing utilities, measuring time
from transformers import AutoTokenizer  # 🤗 Load pretrained tokenizers from HuggingFace with one line

from dataclasses import dataclass  # 🧱 Define simple classes for configs with less boilerplate
from typing import List, Optional  # ✍️ Type hints for better readability and tooling

import warnings  # ⚠️ Suppress or handle warnings
import os  # 🗂️ File system operations (creating folders, path checking, etc.)
import pickle  # 💾 Python object serialization (used to save/load preprocessed datasets)

warnings.filterwarnings('ignore')  # Silences warnings for cleaner outputs during training


In [23]:

def set_seed(seed: int = 42):
    """Set all random seeds for reproducibility"""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False
    print(f"🌱 Set all seeds to {seed}")


In [60]:
@dataclass
class ModelConfig:
    # Model architecture
    d_model: int = 384
    n_heads: int = 8
    n_layers: int = 6
    d_ff: int = 1536
    batch_size: int = 24
    max_steps: int = 2000

    # Qwen3-like parameters
    n_kv_heads: int = 4  # For Grouped-Query Attention
    sliding_window: int = 4096  # Set a large default, effectively disabling it unless specified
    attention_bias: bool = False  # Qwen3 often sets this to False
    rms_norm_eps: float = 1e-6  # Epsilon for RMSNorm

    # Training parameters
    gradient_accumulation_steps: int = 4
    muon_lr: float = 0.001   # orig 0.01

    # Data parameters
    max_seq_len: int = 512
    num_documents: int = 2000
    max_tokens: int = 500000

    # Evaluation
    eval_every: int = 500
    eval_steps: int = 100

    # Regularization
    weight_decay: float = 0.1
    dropout: float = 0.1
    grad_clip: float = 1.0

    # Technical
    use_amp: bool = True
    vocab_size: Optional[int] = None

    def __post_init__(self):
        self.d_k = self.d_model // self.n_heads
        assert self.d_model % self.n_heads == 0, "d_model must be divisible by n_heads"
        assert self.n_heads % self.n_kv_heads == 0, "n_heads must be divisible by n_kv_heads"
        self.n_kv_groups = self.n_heads // self.n_kv_heads

In [25]:
def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep).
    The hidden states go from (batch, num_key_value_heads, seqlen, head_dim)
    to (batch, num_attention_heads, seqlen, head_dim)
    """
    # Extract dimensions from input tensor
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape

    # Early return if no repetition is needed
    if n_rep == 1:
        return hidden_states

    # Add a new dimension at index 2 (after num_key_value_heads) and expand
    # Shape transformation:
    # (batch, num_key_value_heads, slen, head_dim)
    # -> (batch, num_key_value_heads, 1, slen, head_dim) [via None indexing]
    # -> (batch, num_key_value_heads, n_rep, slen, head_dim) [via expand]
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)

    # Flatten the num_key_value_heads and n_rep dimensions together
    # Final shape: (batch, num_key_value_heads * n_rep, slen, head_dim)
    # This effectively repeats each key/value head n_rep times
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)

In [26]:
# Tensor Expansion and Repetition Practice Exercises

import torch
import numpy as np

print("🚀 Tensor Expansion and Repetition Exercises")
print("=" * 50)

# =============================================================================
# EXERCISE 1: Basic Tensor Creation and Shapes
# =============================================================================
print("\n📝 Exercise 1: Understanding Tensor Shapes")
print("-" * 40)

# Create simple tensors and understand their shapes
x = torch.tensor([1, 2, 3])
print(f"1D tensor: {x}")
print(f"Shape: {x.shape}")

y = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"2D tensor:\n{y}")
print(f"Shape: {y.shape}")

z = torch.tensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(f"3D tensor:\n{z}")
print(f"Shape: {z.shape}")

# TODO: Create a 4D tensor of shape (2, 3, 4, 5) filled with ones
# Your code here:
# tensor_4d = ?

🚀 Tensor Expansion and Repetition Exercises

📝 Exercise 1: Understanding Tensor Shapes
----------------------------------------
1D tensor: tensor([1, 2, 3])
Shape: torch.Size([3])
2D tensor:
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])
3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])


In [27]:
# =============================================================================
# EXERCISE 2: Understanding None Indexing (Adding Dimensions)
# =============================================================================
print("\n\n📝 Exercise 2: Adding Dimensions with None")
print("-" * 40)

# Start with a 1D tensor
a = torch.tensor([1, 2, 3, 4])
print(f"Original: {a.shape} -> {a}")

# Add dimension at different positions
a_new_dim0 = a[None, :]  # or a.unsqueeze(0)
print(f"Add dim at 0: {a_new_dim0.shape} -> {a_new_dim0}")

a_new_dim1 = a[:, None]  # or a.unsqueeze(1)
print(f"Add dim at 1: {a_new_dim1.shape} -> {a_new_dim1}")

a_new_dim_end = a[..., None]  # or a.unsqueeze(-1)
print(f"Add dim at end: {a_new_dim_end.shape} -> {a_new_dim_end}")

# Multiple dimensions
a_multi = a[None, :, None, None]
print(f"Multiple dims: {a_multi.shape}")

# TODO: Take tensor [1, 2, 3] and make it shape (1, 3, 1, 1)
# Your code here:
# result = ?



📝 Exercise 2: Adding Dimensions with None
----------------------------------------
Original: torch.Size([4]) -> tensor([1, 2, 3, 4])
Add dim at 0: torch.Size([1, 4]) -> tensor([[1, 2, 3, 4]])
Add dim at 1: torch.Size([4, 1]) -> tensor([[1],
        [2],
        [3],
        [4]])
Add dim at end: torch.Size([4, 1]) -> tensor([[1],
        [2],
        [3],
        [4]])
Multiple dims: torch.Size([1, 4, 1, 1])


In [28]:
# =============================================================================
# EXERCISE 3: Basic expand() Operation
# =============================================================================
print("\n\n📝 Exercise 3: Understanding expand()")
print("-" * 40)

# expand() creates a view with repeated elements (no memory copy!)
b = torch.tensor([[1, 2, 3]])  # Shape: (1, 3)
print(f"Original: {b.shape} -> {b}")

# Expand the first dimension
b_expanded = b.expand(4, 3)  # Repeat the row 4 times
print(f"Expanded: {b_expanded.shape}")
print(b_expanded)

# Expand with -1 (keep original size)
c = torch.tensor([[1], [2], [3]])  # Shape: (3, 1)
print(f"\nOriginal c: {c.shape}")
print(c)

c_expanded = c.expand(-1, 5)  # Keep dim 0, expand dim 1 to 5
print(f"Expanded c: {c_expanded.shape}")
print(c_expanded)

# TODO: Create tensor [[1, 2]] and expand it to shape (3, 4)
# Your code here:
# d = ?
# d_expanded = ?



📝 Exercise 3: Understanding expand()
----------------------------------------
Original: torch.Size([1, 3]) -> tensor([[1, 2, 3]])
Expanded: torch.Size([4, 3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])

Original c: torch.Size([3, 1])
tensor([[1],
        [2],
        [3]])
Expanded c: torch.Size([3, 5])
tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3]])


In [29]:
# =============================================================================
# EXERCISE 4: repeat() vs expand() vs repeat_interleave()
# =============================================================================
print("\n\n📝 Exercise 4: Different Repetition Methods")
print("-" * 40)

original = torch.tensor([1, 2, 3])
print(f"Original: {original}")

# Method 1: repeat() - actually copies data
repeated = original.repeat(2)  # Repeat entire tensor 2 times
print(f"repeat(2): {repeated}")

repeated_2d = original.repeat(2, 1)  # 2D repetition
print(f"repeat(2, 1) on [1,2,3]: shape {repeated_2d.shape}")
print(repeated_2d)

# Method 2: expand() - creates view (memory efficient)
original_2d = original.unsqueeze(0)  # Make it (1, 3)
expanded = original_2d.expand(3, -1)
print(f"expand(3, -1): shape {expanded.shape}")
print(expanded)

# Method 3: repeat_interleave() - repeats each element
interleaved = torch.repeat_interleave(original, 2)
print(f"repeat_interleave(2): {interleaved}")

# TODO: What's the difference between these results?
# torch.tensor([1, 2]).repeat(3) vs torch.repeat_interleave(torch.tensor([1, 2]), 3)



📝 Exercise 4: Different Repetition Methods
----------------------------------------
Original: tensor([1, 2, 3])
repeat(2): tensor([1, 2, 3, 1, 2, 3])
repeat(2, 1) on [1,2,3]: shape torch.Size([2, 3])
tensor([[1, 2, 3],
        [1, 2, 3]])
expand(3, -1): shape torch.Size([3, 3])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
repeat_interleave(2): tensor([1, 1, 2, 2, 3, 3])


In [30]:
# =============================================================================
# EXERCISE 5: Working with 3D Tensors
# =============================================================================
print("\n\n📝 Exercise 5: 3D Tensor Manipulations")
print("-" * 40)

# Create a 3D tensor: (batch=2, heads=3, features=4)
tensor_3d = torch.arange(24).reshape(2, 3, 4)
print(f"3D tensor shape: {tensor_3d.shape}")
print(f"3D tensor:\n{tensor_3d}")

# Add a dimension in the middle
tensor_4d = tensor_3d[:, :, None, :]  # Shape: (2, 3, 1, 4)
print(f"\nAfter adding dim: {tensor_4d.shape}")

# Expand the new dimension
tensor_expanded = tensor_4d.expand(2, 3, 5, 4)  # Shape: (2, 3, 5, 4)
print(f"After expand: {tensor_expanded.shape}")
print(f"First batch, first head:\n{tensor_expanded[0, 0]}")

# TODO: Take the expanded tensor and reshape it to merge dimensions 1 and 2
# Target shape: (2, 15, 4)  # 3 * 5 = 15
# Your code here:
# merged = ?




📝 Exercise 5: 3D Tensor Manipulations
----------------------------------------
3D tensor shape: torch.Size([2, 3, 4])
3D tensor:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

After adding dim: torch.Size([2, 3, 1, 4])
After expand: torch.Size([2, 3, 5, 4])
First batch, first head:
tensor([[0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3],
        [0, 1, 2, 3]])


In [31]:
# =============================================================================
# EXERCISE 6: Simulating the repeat_kv Pattern
# =============================================================================
print("\n\n📝 Exercise 6: Building Up to repeat_kv")
print("-" * 40)

# Simulate key/value heads that need to be repeated
# Shape: (batch, num_kv_heads, seq_len, head_dim)
kv_tensor = torch.arange(48).reshape(2, 3, 4, 2)
print(f"KV tensor shape: {kv_tensor.shape}")
print(f"KV tensor (batch 0, head 0):\n{kv_tensor[0, 0]}")

n_rep = 2  # Each KV head needs to be repeated 2 times

# Step 1: Add dimension for repetition
step1 = kv_tensor[:, :, None, :, :]  # Shape: (2, 3, 1, 4, 2)
print(f"\nStep 1 - Add dimension: {step1.shape}")

# Step 2: Expand the new dimension
step2 = step1.expand(2, 3, n_rep, 4, 2)  # Shape: (2, 3, 2, 4, 2)
print(f"Step 2 - Expand: {step2.shape}")

# Step 3: Reshape to merge heads
final = step2.reshape(2, 3 * n_rep, 4, 2)  # Shape: (2, 6, 4, 2)
print(f"Step 3 - Final: {final.shape}")

# Verify: each original head should appear n_rep times
print(f"\nOriginal head 0:\n{kv_tensor[0, 0]}")
print(f"Repeated head 0 (position 0):\n{final[0, 0]}")
print(f"Repeated head 0 (position 1):\n{final[0, 1]}")
print(f"Original head 1:\n{kv_tensor[0, 1]}")
print(f"Repeated head 1 (position 2):\n{final[0, 2]}")

# TODO: Verify that final[0, 0] equals final[0, 1] (same repeated head)



📝 Exercise 6: Building Up to repeat_kv
----------------------------------------
KV tensor shape: torch.Size([2, 3, 4, 2])
KV tensor (batch 0, head 0):
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])

Step 1 - Add dimension: torch.Size([2, 3, 1, 4, 2])
Step 2 - Expand: torch.Size([2, 3, 2, 4, 2])
Step 3 - Final: torch.Size([2, 6, 4, 2])

Original head 0:
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
Repeated head 0 (position 0):
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
Repeated head 0 (position 1):
tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7]])
Original head 1:
tensor([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])
Repeated head 1 (position 2):
tensor([[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]])


In [32]:
# =============================================================================
# EXERCISE 7: Complete repeat_kv Implementation Practice
# =============================================================================
print("\n\n📝 Exercise 7: Implement repeat_kv Yourself")
print("-" * 40)

def my_repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    TODO: Implement this function!
    Input: (batch, num_key_value_heads, seqlen, head_dim)
    Output: (batch, num_key_value_heads * n_rep, seqlen, head_dim)
    """
    # Get dimensions
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape

    # Handle n_rep = 1 case
    if n_rep == 1:
        return hidden_states

    # TODO: Your implementation here
    # Step 1: Add dimension
    # Step 2: Expand
    # Step 3: Reshape
    # return ?
    pass

# Test your implementation
test_tensor = torch.arange(24).reshape(1, 3, 4, 2)
print(f"Test input shape: {test_tensor.shape}")

# TODO: Uncomment when you implement the function
# result = my_repeat_kv(test_tensor, 2)
# print(f"Result shape: {result.shape}")



📝 Exercise 7: Implement repeat_kv Yourself
----------------------------------------
Test input shape: torch.Size([1, 3, 4, 2])


In [33]:
# =============================================================================
# EXERCISE 8: Advanced Patterns
# =============================================================================
print("\n\n📝 Exercise 8: Advanced Repetition Patterns")
print("-" * 40)

# Pattern 1: Repeat different amounts for different dimensions
base = torch.tensor([[1, 2], [3, 4]])  # Shape: (2, 2)
print(f"Base tensor:\n{base}")

# Repeat 3 times along dim 0, 2 times along dim 1
pattern1 = base.repeat(3, 2)
print(f"Pattern 1 - repeat(3, 2):\n{pattern1}")

# Pattern 2: Using repeat_interleave along specific dimensions
pattern2 = torch.repeat_interleave(base, 2, dim=0)
print(f"Pattern 2 - repeat_interleave along dim 0:\n{pattern2}")

pattern3 = torch.repeat_interleave(base, 2, dim=1)
print(f"Pattern 3 - repeat_interleave along dim 1:\n{pattern3}")

# TODO: Create a pattern where you repeat_interleave along dim 0 with repeats [1, 3]
# (first row once, second row three times)




📝 Exercise 8: Advanced Repetition Patterns
----------------------------------------
Base tensor:
tensor([[1, 2],
        [3, 4]])
Pattern 1 - repeat(3, 2):
tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])
Pattern 2 - repeat_interleave along dim 0:
tensor([[1, 2],
        [1, 2],
        [3, 4],
        [3, 4]])
Pattern 3 - repeat_interleave along dim 1:
tensor([[1, 1, 2, 2],
        [3, 3, 4, 4]])


In [34]:
# =============================================================================
# EXERCISE 9: Memory Efficiency Test
# =============================================================================
print("\n\n📝 Exercise 9: Memory Usage Comparison")
print("-" * 40)

large_tensor = torch.randn(100, 50)
print(f"Original tensor memory: {large_tensor.numel() * large_tensor.element_size()} bytes")

# Method 1: expand (memory efficient - creates view)
expanded = large_tensor.unsqueeze(0).expand(10, -1, -1)
print(f"Expanded tensor shares memory: {expanded.storage().data_ptr() == large_tensor.storage().data_ptr()}")

# Method 2: repeat (creates copy)
repeated = large_tensor.repeat(10, 1)
print(f"Repeated tensor shares memory: {repeated.storage().data_ptr() == large_tensor.storage().data_ptr()}")

# TODO: What happens if you modify the original tensor? Will the expanded version change too?




📝 Exercise 9: Memory Usage Comparison
----------------------------------------
Original tensor memory: 20000 bytes
Expanded tensor shares memory: True
Repeated tensor shares memory: False


In [35]:
# =============================================================================
# EXERCISE 10: Real-World Application - Attention Mechanism
# =============================================================================
print("\n\n📝 Exercise 10: Attention Mechanism Context")
print("-" * 40)

# Simulate a real attention scenario
batch_size = 2
seq_len = 8
num_query_heads = 12
num_kv_heads = 4  # Fewer KV heads than query heads (Grouped Query Attention)
head_dim = 64

print(f"Scenario: {num_query_heads} query heads, {num_kv_heads} KV heads")
print(f"Need to repeat each KV head {num_query_heads // num_kv_heads} times")

# Create mock key and value tensors
keys = torch.randn(batch_size, num_kv_heads, seq_len, head_dim)
values = torch.randn(batch_size, num_kv_heads, seq_len, head_dim)

print(f"Original keys shape: {keys.shape}")
print(f"Original values shape: {values.shape}")

# Apply repeat_kv to match query heads
n_rep = num_query_heads // num_kv_heads

def repeat_kv_solution(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)

keys_repeated = repeat_kv_solution(keys, n_rep)
values_repeated = repeat_kv_solution(values, n_rep)

print(f"Repeated keys shape: {keys_repeated.shape}")
print(f"Repeated values shape: {values_repeated.shape}")

# TODO: Verify that we now have the same number of heads for keys, values, and queries
print(f"Success! KV heads now match query heads: {keys_repeated.shape[1] == num_query_heads}")

print("\n🎉 Exercises Complete!")
print("Next steps:")
print("1. Try modifying the dimensions and see how shapes change")
print("2. Experiment with different n_rep values")
print("3. Compare memory usage between expand() and repeat()")
print("4. Implement your own version of repeat_kv from scratch!")



📝 Exercise 10: Attention Mechanism Context
----------------------------------------
Scenario: 12 query heads, 4 KV heads
Need to repeat each KV head 3 times
Original keys shape: torch.Size([2, 4, 8, 64])
Original values shape: torch.Size([2, 4, 8, 64])
Repeated keys shape: torch.Size([2, 12, 8, 64])
Repeated values shape: torch.Size([2, 12, 8, 64])
Success! KV heads now match query heads: True

🎉 Exercises Complete!
Next steps:
1. Try modifying the dimensions and see how shapes change
2. Experiment with different n_rep values
3. Compare memory usage between expand() and repeat()
4. Implement your own version of repeat_kv from scratch!


In [36]:
@torch.compile
def zeropower_via_newtonschulz5(G: torch.Tensor, steps: int = 5) -> torch.Tensor:
    """Newton-Schulz iteration to compute the zeroth power / orthogonalization of G."""
    assert G.ndim >= 2
    a, b, c = (3.4445, -4.7750, 2.0315)
    X = G.bfloat16()

    if G.size(-2) > G.size(-1):
        X = X.mT

    X = X / (X.norm(dim=(-2, -1), keepdim=True) + 1e-7)

    for _ in range(steps):
        A = X @ X.mT
        B = b * A + c * A @ A
        X = a * X + B @ X

    if G.size(-2) > G.size(-1):
        X = X.mT

    return X

class Muon(torch.optim.Optimizer):
    """Muon - MomentUm Orthogonalized by Newton-schulz"""
    def __init__(self, params, lr=0.02, momentum=0.95, nesterov=True, ns_steps=5):
        defaults = dict(lr=lr, momentum=momentum, nesterov=nesterov, ns_steps=ns_steps)
        super().__init__(params, defaults)

    @torch.no_grad()
    def step(self):
        for group in self.param_groups:
            for p in group["params"]:
                if p.grad is None:
                    continue

                g = p.grad
                state = self.state[p]

                # Initialize momentum buffer if first time
                if "momentum_buffer" not in state:
                    state["momentum_buffer"] = torch.zeros_like(g)

                buf = state["momentum_buffer"]
                # Update momentum buffer: buf = momentum * buf + (1-momentum) * grad
                buf.lerp_(g, 1 - group["momentum"])
                # Apply Nesterov momentum if enabled, otherwise use standard momentum
                g = g.lerp_(buf, group["momentum"]) if group["nesterov"] else buf
                # Apply zero-power normalization via Newton-Schulz iterations (make it close to orthonormal)
                g = zeropower_via_newtonschulz5(g, steps=group["ns_steps"])
                # Update parameters with adaptive scaling based on parameter shape
                p.add_(g.view_as(p), alpha=-group["lr"] * max(1, p.size(-2) / p.size(-1))**0.5)
                # Updates parameters with an adaptive learning rate that scales based on the parameter tensor's aspect ratio (height/width). For matrices where height > width, it increases the effective learning rate by √(height/width)

In [37]:
def load_and_cache_data(config: ModelConfig, cache_dir: str = "data_cache"):
    """Load and cache tokenized data to avoid reprocessing"""
    os.makedirs(cache_dir, exist_ok=True)
    cache_file = f"{cache_dir}/tokenized_data_{config.num_documents}_{config.max_tokens}.pkl"

    # Check if cached data exists
    if os.path.exists(cache_file):
        print(f"📦 Loading cached data from {cache_file}")
        with open(cache_file, 'rb') as f:
            cached_data = pickle.load(f)

        texts = cached_data['texts']
        tokenizer = cached_data['tokenizer']
        tokens = cached_data['tokens']
        config.vocab_size = tokenizer.vocab_size

        print(f"✅ Loaded {len(texts)} documents, {len(tokens):,} tokens from cache")
        return texts, tokenizer, tokens

    print(f"🔄 Processing new data (will cache for future use)")

    # Load tokenizer
    tokenizer = AutoTokenizer.from_pretrained("HuggingFaceTB/SmolLM-135M")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Load dataset
    dataset = load_dataset("HuggingFaceTB/smollm-corpus", "cosmopedia-v2", split="train", streaming=True)

    texts = []
    for i, item in enumerate(dataset):
        if i >= config.num_documents:
            break
        texts.append(item["text"][:3000])

    print(f"Loaded {len(texts)} documents")

    # Tokenize
    print("Tokenizing texts...")
    all_tokens = []
    for text in tqdm(texts, desc="Tokenizing"):
        tokens = tokenizer.encode(text, add_special_tokens=False)
        all_tokens.extend(tokens)

    tokens = all_tokens[:config.max_tokens]
    print(f"Using {len(tokens):,} tokens")
    config.vocab_size = tokenizer.vocab_size

    # Cache the processed data
    cached_data = {'texts': texts, 'tokenizer': tokenizer, 'tokens': tokens}
    with open(cache_file, 'wb') as f:
        pickle.dump(cached_data, f)

    print(f"💾 Cached data to {cache_file}")
    return texts, tokenizer, tokens


In [38]:
class TextTokenDataset(Dataset):
    def __init__(self, tokens: List[int], seq_len: int = 512):
        self.tokens = tokens
        self.seq_len = seq_len

    def __len__(self):
        return max(0, len(self.tokens) - self.seq_len)

    def __getitem__(self, idx):
        x = torch.tensor(self.tokens[idx:idx + self.seq_len], dtype=torch.long)
        y = torch.tensor(self.tokens[idx + 1:idx + self.seq_len + 1], dtype=torch.long)
        return x, y


In [39]:
class Rotary(nn.Module):
    def __init__(self, dim: int, max_seq_len: int):
        super().__init__()
        angular_freq = (1 / 10000) ** torch.linspace(0, 1, steps=dim//4, dtype=torch.float32)
        angular_freq = torch.cat([angular_freq, angular_freq.new_zeros(dim//4)])
        t = torch.arange(max_seq_len, dtype=torch.float32)
        theta = torch.einsum("i,j -> ij", t, angular_freq)
        self.register_buffer('cos', theta.cos(), persistent=False)
        self.register_buffer('sin', theta.sin(), persistent=False)

    def forward(self, x_BTHD: torch.Tensor):
        assert self.cos.size(0) >= x_BTHD.size(-3)
        cos, sin = self.cos[None, :x_BTHD.size(-3), None, :], self.sin[None, :x_BTHD.size(-3), None, :]
        x1, x2 = x_BTHD.to(dtype=torch.float32).chunk(2, dim=-1)
        y1 = x1 * cos + x2 * sin
        y2 = x1 * (-sin) + x2 * cos
        return torch.cat((y1, y2), 3).type_as(x_BTHD)


In [40]:
class Qwen3Attention(nn.Module):
    def __init__(self, config: ModelConfig):
        super().__init__()
        self.d_model = config.d_model
        self.n_heads = config.n_heads
        self.n_kv_heads = config.n_kv_heads
        self.n_kv_groups = config.n_kv_groups
        self.d_k = config.d_k

        # Separate linear layers for Q, K, V
        self.q_proj = nn.Linear(self.d_model, self.n_heads * self.d_k, bias=config.attention_bias)
        self.k_proj = nn.Linear(self.d_model, self.n_kv_heads * self.d_k, bias=config.attention_bias)
        self.v_proj = nn.Linear(self.d_model, self.n_kv_heads * self.d_k, bias=config.attention_bias)
        self.w_o = nn.Linear(self.d_model, self.d_model, bias=False)

        # QK-Normalization layers
        # Practice RMSNorm 1 on 1 with ChatGPT - https://chatgpt.com/share/68945c86-2dd4-8002-b017-725caab0c107
        self.q_norm = nn.RMSNorm(self.d_k, eps=config.rms_norm_eps)
        self.k_norm = nn.RMSNorm(self.d_k, eps=config.rms_norm_eps)

        self.rotary = Rotary(self.d_k, config.max_seq_len)
        self.dropout = config.dropout

    def forward(self, x):
        batch_size, seq_len = x.size(0), x.size(1)

        # 1. Project Q, K, V separately
        q = self.q_proj(x)
        k = self.k_proj(x)
        v = self.v_proj(x)

        # 2. Reshape into heads
        q = q.view(batch_size, seq_len, self.n_heads, self.d_k)
        k = k.view(batch_size, seq_len, self.n_kv_heads, self.d_k)
        v = v.view(batch_size, seq_len, self.n_kv_heads, self.d_k)

        # 3. Apply QK-Norm
        q = self.q_norm(q)
        k = self.k_norm(k)

        # 4. Apply RoPE
        # Transpose to (batch, seq_len, n_heads, d_k) -> (batch, n_heads, seq_len, d_k) for rotary
        q = self.rotary(q.permute(0, 2, 1, 3)).permute(0, 2, 1, 3)
        k = self.rotary(k.permute(0, 2, 1, 3)).permute(0, 2, 1, 3)

        # Transpose for attention: (batch, seq_len, n_heads, d_k) -> (batch, n_heads, seq_len, d_k)
        Q = q.transpose(1, 2)
        K = k.transpose(1, 2)
        V = v.transpose(1, 2)

        # 5. Repeat K and V heads for GQA
        K = repeat_kv(K, self.n_kv_groups)
        V = repeat_kv(V, self.n_kv_groups)

        # 6. Scaled Dot-Product Attention
        attn_output = F.scaled_dot_product_attention(
            Q, K, V, is_causal=True, dropout_p=self.dropout if self.training else 0.0
        )

        # 7. Reshape and final projection
        attn_output = attn_output.transpose(1, 2).contiguous().view(batch_size, seq_len, self.d_model)
        return self.w_o(attn_output)


In [41]:
class SwiGLUFeedForward(nn.Module):
    def __init__(self, d_model: int, d_ff: int, dropout: float = 0.1):
        super().__init__()
        self.gate_proj = nn.Linear(d_model, d_ff, bias=False)
        self.down_proj = nn.Linear(d_ff, d_model, bias=False)
        self.up_proj = nn.Linear(d_model, d_ff, bias=False)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # Implementation of the SwiGLU activation function
        # F.silu is the Swish activation function
        activated_x = F.silu(self.gate_proj(x)) * self.up_proj(x)
        return self.down_proj(self.dropout(activated_x))


In [42]:
class TransformerBlock(nn.Module):
    def __init__(self, config: ModelConfig):  # Pass the entire config object
        super().__init__()
        self.attention = Qwen3Attention(config)
        self.feed_forward = SwiGLUFeedForward(config.d_model, config.d_ff, config.dropout)
        self.norm1 = nn.RMSNorm(config.d_model, eps=config.rms_norm_eps)
        self.norm2 = nn.RMSNorm(config.d_model, eps=config.rms_norm_eps)
        self.dropout = nn.Dropout(config.dropout)

    def forward(self, x):
        attn_out = self.attention(self.norm1(x))
        x = x + self.dropout(attn_out)
        ff_out = self.feed_forward(self.norm2(x))
        x = x + self.dropout(ff_out)
        return x

In [43]:
class MinimalLLM(nn.Module):
    def __init__(self, config: ModelConfig):
        super().__init__()
        self.config = config

        self.token_embedding = nn.Embedding(config.vocab_size, config.d_model)
        self.position_dropout = nn.Dropout(config.dropout)

        self.transformer_blocks = nn.ModuleList([
            TransformerBlock(config) for _ in range(config.n_layers)
        ])

        self.norm = nn.RMSNorm(config.d_model, eps=config.rms_norm_eps)
        self.output_dropout = nn.Dropout(config.dropout)

        # Tie weights
        # This ties the output layer (`lm_head`) weights to the input token embedding weights so the model shares parameters between input and output, reducing memory and improving generalization.
        # https://chatgpt.com/share/6894683e-ba44-8002-ae82-e42b4afc9d98
        self.lm_head = nn.Linear(config.d_model, config.vocab_size, bias=False)
        self.lm_head.weight = self.token_embedding.weight

        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, x):
        x = self.token_embedding(x) * math.sqrt(self.config.d_model)
        x = self.position_dropout(x)

        for block in self.transformer_blocks:
            x = block(x)

        x = self.norm(x)
        x = self.output_dropout(x)
        logits = self.lm_head(x)
        return logits


In [44]:
def evaluate_model(model: nn.Module, val_loader: DataLoader, config: ModelConfig):
    """Evaluate model performance"""
    model.eval()
    total_loss = 0
    total_tokens = 0
    total_correct = 0

    device = next(model.parameters()).device

    with torch.no_grad():  # Disable gradient computation for evaluation (saves memory and computation)
        for i, (x, y) in enumerate(val_loader):
            # Stop evaluation after specified number of steps to limit eval time
            if i >= config.eval_steps:
                break

            # Move input sequences (x) and target sequences (y) to GPU/device
            x, y = x.to(device), y.to(device)

            # Use automatic mixed precision if enabled (faster training with minimal accuracy loss)
            with autocast(enabled=config.use_amp):
                # Forward pass: get model predictions (logits) for input sequence
                logits = model(x)

                # Calculate cross-entropy loss between predictions and targets
                # Reshape to (batch_size * seq_len, vocab_size) and (batch_size * seq_len,)
                # for proper cross-entropy computation across all token positions
                loss = F.cross_entropy(logits.view(-1, config.vocab_size), y.view(-1))

            # Accumulate total loss weighted by number of tokens in this batch
            total_loss += loss.item() * y.numel()
            # Keep track of total number of tokens processed
            total_tokens += y.numel()

            # Get predicted token IDs by taking argmax over vocabulary dimension
            predictions = logits.argmax(dim=-1)
            # Count correct predictions for accuracy calculation
            total_correct += (predictions == y).sum().item()

    avg_loss = total_loss / total_tokens
    accuracy = total_correct / total_tokens
    perplexity = math.exp(min(avg_loss, 20))

    model.train()
    return {'val_loss': avg_loss, 'val_accuracy': accuracy, 'val_perplexity': perplexity}

In [45]:
def setup_muon_optimizer(model: nn.Module, config: ModelConfig):
    """Setup Muon optimizer with hybrid approach"""
    muon_params = []
    adamw_params = []

    for name, param in model.named_parameters():
        if (param.ndim == 2 and
            'token_embedding' not in name and
            'norm' not in name and
            param.requires_grad):
            muon_params.append(param)
        else:
            adamw_params.append(param)

    print(f"  Muon parameters: {sum(p.numel() for p in muon_params):,}")
    print(f"  AdamW parameters: {sum(p.numel() for p in adamw_params):,}")

    muon_optimizer = Muon(muon_params, lr=config.muon_lr, momentum=0.95)
    adamw_optimizer = torch.optim.AdamW(adamw_params, lr=config.muon_lr*0.1, weight_decay=config.weight_decay)

    return [muon_optimizer, adamw_optimizer]


In [46]:
def train_model(config: ModelConfig, train_loader: DataLoader, val_loader: DataLoader):
    """Train the model with Muon optimizer"""
    print(f"\n🚀 Training Small model with Muon optimizer")

    # Initialize model
    set_seed(42)
    model = MinimalLLM(config)
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)

    total_params = sum(p.numel() for p in model.parameters())
    print(f"  📊 Total parameters: {total_params:,}")

    # Setup optimizers
    optimizers = setup_muon_optimizer(model, config)

    # Learning rate schedule
    schedulers = []
    for optimizer in optimizers:
        warmup_steps = config.max_steps // 20
        def lr_lambda(step):
            if step < warmup_steps:
                return step / warmup_steps
            else:
                progress = (step - warmup_steps) / (config.max_steps - warmup_steps)
                return 0.1 + 0.9 * 0.5 * (1 + math.cos(math.pi * progress))

        scheduler = torch.optim.lr_scheduler.LambdaLR(optimizer, lr_lambda)
        schedulers.append(scheduler)

    scaler = GradScaler() if config.use_amp else None

    # Training loop
    model.train()
    step = 0
    start_time = time.time()
    best_val_loss = float('inf')

    pbar = tqdm(total=config.max_steps, desc="Training")

    while step < config.max_steps:
        for batch_idx, (x, y) in enumerate(train_loader):
            if step >= config.max_steps:
                break

            x, y = x.to(device), y.to(device)

            # Forward pass with gradient accumulation
            if config.use_amp:
                with autocast():
                    logits = model(x)
                    loss = F.cross_entropy(logits.view(-1, config.vocab_size), y.view(-1))
                    loss = loss / config.gradient_accumulation_steps
                scaler.scale(loss).backward()
            else:
                logits = model(x)
                loss = F.cross_entropy(logits.view(-1, config.vocab_size), y.view(-1))
                loss = loss / config.gradient_accumulation_steps
                loss.backward()

            # Optimizer step after accumulation
            if (step + 1) % config.gradient_accumulation_steps == 0:
                if config.use_amp:
                    for optimizer in optimizers:
                        scaler.unscale_(optimizer)
                    grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip)

                    for optimizer in optimizers:
                        scaler.step(optimizer)
                        optimizer.zero_grad()
                    for scheduler in schedulers:
                        scheduler.step()
                    scaler.update()
                else:
                    grad_norm = torch.nn.utils.clip_grad_norm_(model.parameters(), config.grad_clip)
                    for optimizer in optimizers:
                        optimizer.step()
                        optimizer.zero_grad()
                    for scheduler in schedulers:
                        scheduler.step()

            # Logging
            if step % 10 == 0:
                with torch.no_grad():
                    predictions = logits.argmax(dim=-1)
                    accuracy = (predictions == y).float().mean().item()
                    current_loss = loss.item() * config.gradient_accumulation_steps
                    perplexity = math.exp(min(current_loss, 20))

                pbar.set_postfix({
                    'loss': f'{current_loss:.4f}',
                    'acc': f'{accuracy:.3f}',
                    'ppl': f'{perplexity:.1f}',
                    'lr': f'{optimizers[0].param_groups[0]["lr"]:.2e}'
                })

            # Evaluation
            if step % config.eval_every == 0 and step > 0:
                eval_metrics = evaluate_model(model, val_loader, config)
                print(f"\nStep {step}: Val Loss: {eval_metrics['val_loss']:.4f}, "
                      f"Val Acc: {eval_metrics['val_accuracy']:.4f}, "
                      f"Val PPL: {eval_metrics['val_perplexity']:.2f}")

                if eval_metrics['val_loss'] < best_val_loss:
                    best_val_loss = eval_metrics['val_loss']
                    # Save best model
                    torch.save({
                        'model_state_dict': model.state_dict(),
                        'config': config,
                        'step': step,
                        'best_val_loss': best_val_loss,
                        'final_metrics': eval_metrics
                    }, 'best_model.pt')
                    print(f"💾 Saved best model with val_loss: {best_val_loss:.4f}")

            step += 1
            if step % 10 == 0:
                pbar.update(10)

    pbar.close()

    training_time = time.time() - start_time
    print(f"  ⏱️ Training completed in {training_time:.1f} seconds")

    # Final evaluation
    final_eval = evaluate_model(model, val_loader, config)
    print(f"  📊 Final - Loss: {final_eval['val_loss']:.4f}, "
          f"Acc: {final_eval['val_accuracy']:.4f}, PPL: {final_eval['val_perplexity']:.2f}")

    # Save final model
    torch.save({
        'model_state_dict': model.state_dict(),
        'config': config,
        'step': step,
        'final_metrics': final_eval
    }, 'final_model.pt')
    print(f"💾 Saved final model to final_model.pt")

    return model, final_eval


In [61]:
if __name__ == "__main__":
    # Check system
    print(f"🔍 Device: {'CUDA' if torch.cuda.is_available() else 'CPU'}")
    if torch.cuda.is_available():
        print(f"GPU: {torch.cuda.get_device_name()}")
        print(f"Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB")

    # Set seed
    set_seed(42)

    # Create config for Small model
    config = ModelConfig()
    print(f"\n📋 Model Configuration:")
    print(f"   Architecture: {config.d_model}d, {config.n_layers}L, {config.n_heads}H, {config.d_ff}ff")
    print(f"   Training: {config.max_steps} steps, batch size {config.batch_size}")
    print(f"   Data: {config.max_tokens:,} tokens, seq_len {config.max_seq_len}")

    # Load data
    texts, tokenizer, tokens = load_and_cache_data(config)
    dataset = TextTokenDataset(tokens, config.max_seq_len)

    # Train/val split
    val_size = len(dataset) // 10
    train_size = len(dataset) - val_size
    train_dataset, val_dataset = torch.utils.data.random_split(
        dataset, [train_size, val_size], generator=torch.Generator().manual_seed(42)
    )

    train_loader = DataLoader(train_dataset, batch_size=config.batch_size, shuffle=True, num_workers=2)
    val_loader = DataLoader(val_dataset, batch_size=config.batch_size, shuffle=False, num_workers=2)

    print(f"📊 Dataset: {len(train_dataset)} train, {len(val_dataset)} val samples")

    # Train model
    start_time = time.time()
    model, final_metrics = train_model(config, train_loader, val_loader)
    total_time = time.time() - start_time

    print(f"\n🎉 TRAINING COMPLETED!")
    print(f"⏱️ Total time: {total_time/60:.1f} minutes")
    print(f"🏆 Final Results:")
    print(f"   Validation Loss: {final_metrics['val_loss']:.4f}")
    print(f"   Validation Accuracy: {final_metrics['val_accuracy']:.4f}")
    print(f"   Validation Perplexity: {final_metrics['val_perplexity']:.2f}")

🔍 Device: CUDA
GPU: Tesla T4
Memory: 15.8 GB
🌱 Set all seeds to 42

📋 Model Configuration:
   Architecture: 384d, 6L, 8H, 1536ff
   Training: 2000 steps, batch size 24
   Data: 500,000 tokens, seq_len 512
📦 Loading cached data from data_cache/tokenized_data_2000_500000.pkl
✅ Loaded 2000 documents, 500,000 tokens from cache
📊 Dataset: 449540 train, 49948 val samples

🚀 Training Small model with Muon optimizer
🌱 Set all seeds to 42
  📊 Total parameters: 32,150,976
  Muon parameters: 13,271,040
  AdamW parameters: 18,879,936


Training:  25%|██▌       | 500/2000 [02:46<08:26,  2.96it/s, loss=8.0689, acc=0.073, ppl=3193.6, lr=1.00e-03]


Step 500: Val Loss: 7.9587, Val Acc: 0.0754, Val PPL: 2860.45
💾 Saved best model with val_loss: 7.9587


Training:  50%|█████     | 1000/2000 [05:44<05:35,  2.98it/s, loss=6.5456, acc=0.165, ppl=696.2, lr=9.86e-04]


Step 1000: Val Loss: 6.4605, Val Acc: 0.1710, Val PPL: 639.41
💾 Saved best model with val_loss: 6.4605


Training:  75%|███████▌  | 1500/2000 [08:41<02:48,  2.98it/s, loss=5.8510, acc=0.201, ppl=347.6, lr=9.54e-04]


Step 1500: Val Loss: 5.7175, Val Acc: 0.2063, Val PPL: 304.14
💾 Saved best model with val_loss: 5.7175


Training: 100%|██████████| 2000/2000 [11:39<00:00,  2.86it/s, loss=5.3792, acc=0.209, ppl=216.8, lr=9.06e-04]

  ⏱️ Training completed in 699.3 seconds


  📊 Final - Loss: 5.2910, Acc: 0.2304, PPL: 198.55
💾 Saved final model to final_model.pt

🎉 TRAINING COMPLETED!
⏱️ Total time: 11.9 minutes
🏆 Final Results:
   Validation Loss: 5.2910
   Validation Accuracy: 0.2304
   Validation Perplexity: 198.55


In [62]:
def load_trained_model(model_path: str = "final_model.pt"):
    """Load a trained model from checkpoint"""
    print(f" Loading model from {model_path}")

    # Add ModelConfig to safe globals for PyTorch 2.6+
    from torch.serialization import add_safe_globals
    add_safe_globals([ModelConfig])

    try:
        checkpoint = torch.load(model_path, map_location='cpu')
        config = checkpoint['config']
    except Exception as e:
        print(f"⚠️ Error loading with weights_only=True, trying with weights_only=False...")
        checkpoint = torch.load(model_path, map_location='cpu', weights_only=False)
        config = checkpoint['config']

    # Create model with same config
    model = MinimalLLM(config)
    model.load_state_dict(checkpoint['model_state_dict'])

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = model.to(device)
    model.eval()

    print(f"✅ Model loaded successfully")
    print(f"   Parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"   Device: {device}")

    return model, config

In [63]:
!ls -l

total 251248
-rw-r--r-- 1 root root 128634549 Jan 26 02:17 best_model.pt
drwxr-xr-x 2 root root      4096 Jan 26 02:02 data_cache
-rw-r--r-- 1 root root 128634559 Jan 26 02:20 final_model.pt
drwxr-xr-x 1 root root      4096 Dec  9 14:42 sample_data


In [64]:
def generate_text(model: nn.Module, tokenizer, prompt: str, max_length: int = 100,
                 temperature: float = 0.8, top_k: int = 50, top_p: float = 0.9):
    """Generate text using the trained model"""
    model.eval()
    device = next(model.parameters()).device

    # Tokenize prompt
    input_ids = tokenizer.encode(prompt, add_special_tokens=False, return_tensors='pt').to(device)

    generated_ids = input_ids.clone()

    with torch.no_grad():
        for _ in range(max_length):
            # Get model predictions
            logits = model(generated_ids)
            next_token_logits = logits[0, -1, :] / temperature

            # Apply top-k filtering
            if top_k > 0:
                top_k_logits, top_k_indices = torch.topk(next_token_logits, top_k)
                next_token_logits = torch.full_like(next_token_logits, float('-inf'))
                next_token_logits[top_k_indices] = top_k_logits

            # Apply top-p (nucleus) filtering
            if top_p < 1.0:
                sorted_logits, sorted_indices = torch.sort(next_token_logits, descending=True)
                cumulative_probs = torch.cumsum(F.softmax(sorted_logits, dim=-1), dim=-1)
                sorted_indices_to_remove = cumulative_probs > top_p
                sorted_indices_to_remove[1:] = sorted_indices_to_remove[:-1].clone()
                sorted_indices_to_remove[0] = 0
                indices_to_remove = sorted_indices[sorted_indices_to_remove]
                next_token_logits[indices_to_remove] = float('-inf')

            # Sample next token
            probs = F.softmax(next_token_logits, dim=-1)
            next_token = torch.multinomial(probs, num_samples=1)

            # Append to generated sequence - FIX: ensure same dimensions
            next_token = next_token.unsqueeze(0)  # Add batch dimension
            generated_ids = torch.cat([generated_ids, next_token], dim=1)

            # Stop if we reach the end token
            if next_token.item() == tokenizer.eos_token_id:
                break

    # Decode the generated text
    generated_text = tokenizer.decode(generated_ids[0], skip_special_tokens=True)
    return generated_text


In [65]:
def interactive_inference(model_path: str = "final_model.pt"):
    """Interactive inference session"""
    print("🤖 Starting interactive inference session")
    print("Type 'quit' to exit")

    # Load model and tokenizer
    model, config = load_trained_model(model_path)

    # Load tokenizer (assuming we have the same one used during training)
    tokenizer = AutoTokenizer.from_pretrained("HuggingFaceTB/SmolLM-135M")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    while True:
        try:
            prompt = input("\n Enter your prompt: ")
            if prompt.lower() in ['quit', 'exit', 'q']:
                print("👋 Goodbye!")
                break

            if not prompt.strip():
                continue

            print("🔄 Generating...")
            generated_text = generate_text(
                model, tokenizer, prompt,
                max_length=150,
                temperature=0.8,
                top_k=50,
                top_p=0.9
            )

            print(f"\n Generated text:")
            print(f"📝 {generated_text}")

        except KeyboardInterrupt:
            print("\n👋 Goodbye!")
            break
        except Exception as e:
            print(f"❌ Error: {e}")

In [66]:
def demo_inference(model_path: str = "final_model.pt"):
    """Run a quick demo of the model's capabilities"""
    print("🎭 Running inference demo")

    # Load model and tokenizer
    model, config = load_trained_model(model_path)
    tokenizer = AutoTokenizer.from_pretrained("HuggingFaceTB/SmolLM-135M")
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    # Demo prompts
    demo_prompts = [
        "The future of artificial intelligence",
        "Once upon a time in a distant galaxy",
        "The most important thing to remember is",
        "In the year 2050, technology will",
        "The best way to learn programming is"
    ]

    for i, prompt in enumerate(demo_prompts, 1):
        print(f"\n Demo {i}: '{prompt}'")
        print("-" * 50)

        generated_text = generate_text(
            model, tokenizer, prompt,
            max_length=100,
            temperature=0.7,
            top_k=40,
            top_p=0.85
        )

        print(f"📝 {generated_text}")
        print()


In [67]:
if __name__ == "__main__":
    # Check if we have a trained model
    import os

    if os.path.exists("final_model.pt"):
        print("🎉 Found trained model! Running demo...")
        demo_inference("final_model.pt")

        # Optionally run interactive session
        response = input("\n🤖 Would you like to try interactive inference? (y/n): ")
        if response.lower() in ['y', 'yes']:
            interactive_inference("final_model.pt")
    else:
        print("⚠️ No trained model found. Please run the training cells first.")
        print("💡 Look for 'final_model.pt' or 'best_model.pt' in your directory.")


🎉 Found trained model! Running demo...
🎭 Running inference demo
 Loading model from final_model.pt
✅ Model loaded successfully
   Parameters: 32,150,976
   Device: cuda

 Demo 1: 'The future of artificial intelligence'
--------------------------------------------------
📝 The future of artificial intelligence and its its core, and social, and their communities.

**What is essential. For instance, which is a single step in the concept of these concepts, the way to the concept of the world, this unit, and their experiences, and the United States.

* **Unit 2:
* ** **A. By the importance of the same time, these individuals who knows?
* **G-based.
* **G**: These individuals to the United States


 Demo 2: 'Once upon a time in a distant galaxy'
--------------------------------------------------
📝 Once upon a time in a distant galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy galaxy 

In [68]:
!ls ../

bin			    kaggle		      opt		 sys
boot			    lib			      proc		 tmp
content			    lib32		      python-apt	 tools
cuda-keyring_1.1-1_all.deb  lib64		      python-apt.tar.xz  usr
datalab			    libx32		      root		 var
dev			    media		      run
etc			    mnt			      sbin
home			    NGC-DL-CONTAINER-LICENSE  srv


In [69]:
!cat /etc/os-release

PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy


In [70]:
!python -V

Python 3.12.12


In [71]:
!nvidia-smi

Mon Jan 26 02:23:06 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.15              Driver Version: 550.54.15      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   76C    P0             34W /   70W |   11754MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [72]:
import tensorflow as tf
device_name = tf.test.gpu_device_name()
if device_name:
    print('Found GPU at: {}'.format(device_name))
else:
    print('GPU device not found')


Found GPU at: /device:GPU:0


In [73]:
pip freeze

absl-py==1.4.0
accelerate==1.12.0
access==1.1.10.post3
affine==2.4.0
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.3
aiosignal==1.4.0
aiosqlite==0.22.1
alabaster==1.0.0
albucore==0.0.24
albumentations==2.0.8
ale-py==0.11.2
alembic==1.18.1
altair==5.5.0
annotated-doc==0.0.4
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.12.1
anywidget==0.9.21
apsw==3.51.2.0
apswutils==0.1.2
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
array_record==0.8.3
arrow==1.4.0
arviz==0.22.0
astropy==7.2.0
astropy-iers-data==0.2026.1.12.0.42.13
astunparse==1.6.3
atpublic==5.1
attrs==25.4.0
audioread==3.1.0
Authlib==1.6.6
autograd==1.8.0
babel==2.17.0
backcall==0.2.0
beartype==0.22.9
beautifulsoup4==4.13.5
betterproto==2.0.0b6
bigframes==2.31.0
bigquery-magics==0.10.3
bleach==6.3.0
blinker==1.9.0
blis==1.3.3
blobfile==3.1.0
blosc2==3.12.2
bokeh==3.7.3
Bottleneck==1.4.2
bqplot==0.12.45
branca==0.8.2
brotli==1.2.0
CacheControl==0.14.4
cachetools==6.2.4
catalogue==2.0.10
certifi==2026.1.4
c